import { Book } from '../types';

// Real Project Gutenberg plain-text URLs — taken directly from the Gutendex
// formats object, not constructed manually.
export const demoBooks: Book[] = [
  {
    id: 'demo-pride-and-prejudice',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    coverUrl: 'https://covers.openlibrary.org/b/id/8231856-L.jpg',
    description:
      'A witty public-domain classic following Elizabeth Bennet, family expectations, first impressions, and a famously complicated romance.',
    sourceType: 'gutenberg',
    textUrl: 'https://www.gutenberg.org/files/1342/1342-0.txt',
    fileUri: null,
    textCacheUri: null,
    pdfUrl: null,
    pdfLocalPath: null,
    progress: 0.38,
    currentChunkIndex: 7,
    sectionType: 'section',
    sections: [],
    currentSectionIndex: 0,
    status: 'listening',
    voice: 'nova',
    speed: 1.25,
    dateAdded: '2026-05-05T00:00:00.000Z',
    lastOpenedAt: null,
  },
  {
    id: 'demo-sherlock-holmes',
    title: 'The Adventures of Sherlock Holmes',
    author: 'Arthur Conan Doyle',
    coverUrl: 'https://covers.openlibrary.org/b/id/8237641-L.jpg',
    description:
      'A collection of detective stories that works well as short listening sessions while driving.',
    sourceType: 'gutenberg',
    textUrl: 'https://www.gutenberg.org/files/1661/1661-0.txt',
    fileUri: null,
    textCacheUri: null,
    pdfUrl: null,
    pdfLocalPath: null,
    progress: 0.12,
    currentChunkIndex: 2,
    sectionType: 'section',
    sections: [],
    currentSectionIndex: 0,
    status: 'reading',
    voice: 'echo',
    speed: 1,
    dateAdded: '2026-05-05T00:00:00.000Z',
    lastOpenedAt: null,
  },
  {
    id: 'demo-frankenstein',
    title: 'Frankenstein',
    author: 'Mary Wollstonecraft Shelley',
    coverUrl: 'https://covers.openlibrary.org/b/id/8390561-L.jpg',
    description:
      'A gothic public-domain novel included to demonstrate completed-book progress and library status styling.',
    sourceType: 'gutenberg',
    textUrl: 'https://www.gutenberg.org/files/84/84-0.txt',
    fileUri: null,
    textCacheUri: null,
    pdfUrl: null,
    pdfLocalPath: null,
    progress: 1,
    currentChunkIndex: 24,
    sectionType: 'section',
    sections: [],
    currentSectionIndex: 0,
    status: 'completed',
    voice: 'fable',
    speed: 1.5,
    dateAdded: '2026-05-05T00:00:00.000Z',
    lastOpenedAt: null,
  },
];
